[theme]
theme = "nord-dark"

[icons]
icons = "material-nf"
[[block]]
block = "sound"
format = " $icon $volume.eng(w:2) "
step_width = 5
max_vol = 100
[[block]]
block = "battery"
format = " $icon $percentage "
full_threshold = 80

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
format = " $icon $utilization "

[[block]]
block = "temperature"
format = " $icon $max max "
chip = "coretemp-isa-0000"
interval = 5

[[block]]
block = "menu"
text = "\uf011"

[[block.items]]
display = " ->   Sleep   <-"
cmd = "systemctl suspend"

[[block.items]]
display = " -> Power Off <-"
cmd = "poweroff"
confirm_msg = "Are you sure you want to power off?"

[[block.items]]
display = " ->  Reboot   <-"
cmd = "reboot"
confirm_msg = "Are you sure you want to reboot?"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:en_US) "
